services:
  frontend:
    build:
      context: ./app/stockAI-frontend
    volumes:
      - ./app/stockAI-frontend:/app
    ports:
      - "3006:3006"  # Frontend Dev Server
    environment:
      - NODE_ENV=development
      - TZ=Europe/Lisbon
    networks:
      - stock-ai
  
  backend:
    build:
      context: ./app/stockAI-backend
      dockerfile: Dockerfile
    volumes:
      - ./app/stockAI-backend:/app
    ports:
      - "8000:8000"  # Backend API
    networks:
      - stock-ai

  database:
    build:
      context: ./app/database
      dockerfile: Dockerfile
    volumes:
      - ./app/database:/app
    ports:
      - "3000:3000"  # Backend API
    networks:
      - stock-ai

networks: 
  stock-ai:
    name: stock-ai
