version: '3.8'

services:
  dev-environment:
    build: .
    container_name: ubuntu-dev-container
    hostname: dev-server
    volumes:
      - ./app:/app
      - ./data:/data
    ports:
      - "3000:3000"  # JSON Server
      - "8000:8000"  # Python HTTP Server
      - "8080:8080"  # PHP Built-in Server
    environment:
      - NODE_ENV=development
      - TZ=Europe/Lisbon
    working_dir: /app
    command: >
      sh -c "
        echo 'Starting JSON Server on port 3000...' &&
        json-server --watch stockAI-backend/db.json --port 3000 --host 0.0.0.0 &
        echo 'Starting PHP server on port 8080...' &&
        php -S 0.0.0.0:8080 -t /app &
        echo 'Starting FastAPI application on port 8000...' &&
        python3 stockAI-backend/receipt/receipt_reader.py
      "
    restart: unless-stopped